---
title: "Statistical Performance Indicators Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny  
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
library(leaflet)
library(wbstats)
library(rgdal)
library(geojsonio)
library(DT)
library(skimr)
library(ggcorrplot)
library(Hmisc)
library(flextable)
library(skimr)
library(here)

```

```{r global, include=FALSE}
#read in data and metatdata
SPI <- read_csv('SPI_index.csv')

metadata_raw <- read_csv('SPI_dimensions_sources.csv')

metadata <- metadata_raw %>%
    mutate(descript=paste(SPI_indicator_id,": ", spi_indicator_name," - ",source_name , sep="")) %>%
    select(source_id,  descript, spi_indicator_description,spi_indicator_scoring)

metadata <- read_csv('SPI_index_sources.csv') %>%
  bind_rows(metadata)


#create named list, which can be useful later
var.labels <- metadata$descript
names(var.labels) <- metadata$source_id

#read in TopoJSON from World Bank
countries <- geojsonio::geojson_read("WB_countries_Admin0_lowres.geojson",
                                     what = "sp")

#country info
country_info <- wb_countries() %>%
    mutate(income=income_level,
           lending=lending_type) %>%
    filter(region!="Aggregates") %>%
    select(iso3c, country, region, income, lending)
```
Column {.sidebar}
-----------------------------------------------------------------------

The Statistical Performance Indicators (SPI) framework is designed to capture different aspects of national
statistical capacity by employing most relevant and representative
variables that are publicly available. The SPI can be used to gauge
statistical performance of individual countries over time or
cross-country comparisons of performance at a point in time.

Select an indicator and year to explore below.

```{r}



selectizeInput("indicator_overall", "Choose Indicator", 
               choices=metadata$descript,
               selected='SPI.INDEX') 


selectizeInput("year_overall",
               "Reference Year",
               choices=c(2004:2019),
               selected=2019)

uiOutput("downloadUI")
```

```{r}

# Create the actual downloadButton
output$downloadUI <- renderUI( {
  downloadButton("downloadDataMap", "Download SPI Data", style = "width:100%;")
})

output$downloadDataMap <- downloadHandler(
    filename = "SPI.csv",
    content = function(file) {
      write.csv(SPI, file)
    }

    )

```



Column {data-width=650}
-----------------------------------------------------------------------

### SPI Map

```{r}

df_overall<- reactive({
  SPI %>%
    select(iso3c, country, region,  income, date, starts_with('SPI'), population) %>%
    filter(date==input$year_overall) 
  
  
  
})

# updateSelectizeInput(session, 'indicator_overall', choices = c('SPI.OVRL.SCR', 'SPI.D1.MSC', 'SPI.D2.CS', 'SPI.D3.AKI', 'SPI.D4.DPO'), server = TRUE)

map_var <- reactive({
  
  names(var.labels[match(input$indicator_overall, var.labels)])
  
})

renderLeaflet({
  
  
  spi_map_overall<-countries
  
  spi_map_overall@data <- spi_map_overall@data %>%
    mutate(iso3c=ISO_A3_EH,
           iso3c=if_else(ISO_A3_EH==-99,WB_A3,ISO_A3_EH)) %>%
    left_join(df_overall()) 
  
  palette_df <- df_overall() %>%
    select(map_var())
  
  brks <- quantile(palette_df[,1], probs=c(1,2,3,4)/5,na.rm=T)
  brks <- append(0,brks)
  col_p <- c("#ff9f1c","#ffbf69","#f1dc76","#acece7")
  
  if (max(brks)<100) {
    brks <- append(brks,100)
    col_p <- c("#ff9f1c","#ffbf69","#f1dc76","#acece7","#2ec4b6")
    
  }        #create pallete
  pal <- colorBin(col_p, 
                  bins=brks,
                  domain=c(0,100),
                  na.color='grey',
                  pretty=FALSE)
  
  
  
  ##############
  #create labels
  ##############
  
  
  labels <- sprintf(
    "<strong>%s</strong><br/> <hr size=2>
            <strong> %s: %g </strong><br/> <hr size=2>
            ",
    spi_map_overall@data$NAME_EN,
    'Indicator Value', round(select(spi_map_overall@data, map_var())[,1], digits = 1)
    
  ) %>%
    lapply(htmltools::HTML)
  
  
  if (grepl('SPI.INDEX',map_var())) {
    
    leaflet(spi_map_overall) %>%
      addProviderTiles(providers$Esri.WorldStreetMap) %>%
      addPolygons(stroke = FALSE, smoothFactor = 0.3, fillOpacity = 0.7,
                  fillColor = ~pal(select(spi_map_overall@data, map_var())[,1]),
                  label=labels) %>%
      addLegend(pal=pal, 
                values=~select(spi_map_overall@data, map_var())[,1], opacity=0.7, 
                labFormat = function(type, cuts, p) {  # Here's the trick
                  paste0( c("Bottom 20%","2nd Quintile","3rd Quintile","4th Quintile","Top 20%" ))
                },
                title='Indicator value', position="bottomleft")      
  } else {
    
    pal <- colorNumeric("Blues", palette_df[,1])
    
    
    leaflet(spi_map_overall) %>%
      addProviderTiles(providers$Esri.WorldStreetMap) %>%
      addPolygons(stroke = FALSE, smoothFactor = 0.3, fillOpacity = 0.7,
                  fillColor = ~pal(select(spi_map_overall@data, map_var())[,1]),
                  label=labels) %>%
      addLegend(pal=pal, 
                values=~select(spi_map_overall@data, map_var())[,1], opacity=0.7, 
                title='Indicator value', position="bottomleft")      
  }
  
  
  
})



```

<!-- ### Time Trends -->

<!-- ```{r} -->
<!-- ############ -->
<!-- # Plot Over Time -->
<!-- ############ -->

<!-- time_var <- reactive({ -->

<!--   names(var.labels[match(input$indicator_overall, var.labels)]) -->

<!-- }) -->

<!-- df_time <- reactive({ -->

<!--   #produce by region -->
<!--   time_df<- SPI %>% -->
<!--     select(iso3c, country, income, date, population, time_var() ) %>% -->
<!--     rename(y=time_var()) %>% -->
<!--     left_join(country_info) %>% -->
<!--     group_by(date, region) %>% -->
<!--     summarise(y=100*mean(y, na.rm=T))  %>% -->
<!--     ungroup()   -->


<!--   #produce global number -->
<!--   time_df_gl<- SPI %>% -->
<!--     select(iso3c, country, date, population, time_var() ) %>% -->
<!--     rename(y=time_var()) %>% -->
<!--     mutate(region='Global') %>% -->
<!--     group_by(date, region) %>% -->
<!--     summarise(y=100*mean(y, na.rm=T)) %>% -->
<!--     ungroup() -->

<!--   #join -->
<!--   time_df <- time_df %>% -->
<!--     bind_rows(time_df_gl)  -->

<!--   if (time_var() %in% c('SPI.INDEX', 'SPI.INDEX.DIM1', 'SPI.INDEX.DIM2', 'SPI.INDEX.DIM3', 'SPI.INDEX.DIM4', 'SPI.INDEX.DIM5')) { -->
<!--     #fix an issue where main variables need to be rescaled -->
<!--     time_df <- time_df %>% -->
<!--       mutate(y=y/100) -->
<!--   } -->

<!--   time_df  -->


<!-- }) -->

<!-- renderPlotly({ -->

<!--   plot_ly(data = df_time(), x = ~date, y = ~y,  -->
<!--           color=~region,  -->
<!--           labels=time_var(), -->
<!--           type = 'scatter', mode = 'lines+markers', -->
<!--           width=1000) %>% -->
<!--     layout(title = paste('Plot of SPI Indicators Over Time by Region: ',input$over_time, sep=""), -->
<!--            xaxis = list(autotick = F, dtick = 1), -->
<!--            yaxis = list(range = c(0,100)), -->
<!--            legend=list(orientation='h')) -->


<!-- }) -->

<!-- ``` -->



<!-- Column {data-width=350} -->
<!-- ----------------------------------------------------------------------- -->

<!-- ### Scores by Dimension -->

<!-- ```{r} -->
<!-- df_dim <- reactive({ -->

<!--   #produce by region -->
<!--   time_df<- SPI %>% -->
<!--     select(iso3c, country, income, date, population, starts_with('SPI.INDEX') ) %>% -->
<!--     filter(date==input$year_overall)  -->


<!--   time_df -->



<!-- }) -->

<!-- renderPlotly({ -->

<!--   ##################### Zipper ############################### -->



<!--   # create dataframe by income -->
<!--   df_aggregated <- df_dim() %>% -->
<!--     ungroup() %>% -->
<!--     filter(!is.na(SPI.INDEX)) %>% -->
<!--     mutate(rank=max(SPI.INDEX)) %>% -->
<!--     arrange(SPI.INDEX)  %>% -->
<!--     ungroup() %>% -->
<!--     mutate(rank = rank(rank, ties.method = 'first')) %>% -->
<!--     arrange(rank) %>% -->
<!--     mutate(Country=factor(rank,  levels=rank, labels=country)) %>% -->
<!--     mutate(across(starts_with("SPI.INDEX"), round,1)) -->


<!--   #plot by dimension -->
<!--   colors <- c("SPI Overall Score" = "#390099", "SPI Dim 1 - Data Use" = "#9b5de5", "SPI Dim 2 - Data Services" = "#f15bb5", "SPI Dim 3 - Data Products" = "#fee440", "SPI Dim 4 - Data Sources" = "#00bbf9", "SPI Dim 5 - Data Infrastructure" = "#00f5d4" ) -->

<!--   zipper_plt<-ggplot(df_aggregated, aes(x=Country, y=SPI.INDEX)) + -->
<!--     geom_segment( aes(x=Country, xend=Country, y=0, yend=100), color="grey", size=1, alpha=0.1) + -->
<!--     geom_point(aes(color="SPI Overall Score"),size=2,) + -->
<!--     geom_point( aes(y=SPI.INDEX.DIM1, color="SPI Dim 1 - Data Use"),size=2,) + -->
<!--     geom_point( aes(y=SPI.INDEX.DIM2, color="SPI Dim 2 - Data Services"), size=2,) + -->
<!--     geom_point( aes(y=SPI.INDEX.DIM3, color="SPI Dim 3 - Data Products"), size=2,) + -->
<!--     geom_point( aes(y=SPI.INDEX.DIM4, color="SPI Dim 4 - Data Sources"), size=2,) + -->
<!--     geom_point( aes(y=SPI.INDEX.DIM5, color="SPI Dim 5 - Data Infrastructure"), size=2,) + -->
<!--     #geom_text(aes(label=food_insecure_mod_severe), nudge_y = 3) + -->
<!--     coord_flip()+ -->
<!--     theme_bw() + -->
<!--     theme( -->
<!--       panel.grid.major.x = element_blank(), -->
<!--       panel.grid.major.y = element_blank(), -->
<!--       panel.grid.minor = element_blank(), -->
<!--       panel.border = element_blank(), -->
<!--       axis.ticks.x = element_blank() -->
<!--     ) + -->
<!--     expand_limits(y=c(0,100)) + -->
<!--     labs( -->
<!--       x="", -->
<!--       y="Statistical Performance Indicator", -->
<!--       color="Legend" -->
<!--     ) + -->
<!--     ggtitle(str_wrap("Statistical Performance Indicator", 120)) +  -->
<!--     # scale_x_continuous( -->
<!--     #   breaks = df_aggregated$rank, # specify tick breaks using rank column -->
<!--     #   labels = df_aggregated$country # specify tick labels using x column -->
<!--     # ) + -->
<!--     scale_color_manual(values = colors, -->
<!--                        breaks=c("SPI Overall Score", "SPI Dim 1 - Data Use", "SPI Dim 2 - Data Services", "SPI Dim 3 - Data Products", "SPI Dim 4 - Data Sources", "SPI Dim 5 - Data Infrastructure"), -->
<!--                        labels=c("SPI Overall Score", "SPI Dim 1 - Data Use", "SPI Dim 2 - Data Services", "SPI Dim 3 - Data Products", "SPI Dim 4 - Data Sources", "SPI Dim 5 - Data Infrastructure")) -->
<!--   zipper_plt -->



<!--   ggplotly(zipper_plt) -->


<!-- }) -->
<!-- ``` -->


